apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-mounting-secret
  labels:
    app: webserver
spec:
  containers:
    - name: demo-pod
      image: zxcvbnius/docker-demo
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /etc/creds
  volumes:
    - name: secret-volume
      secret:
        secretName: demo-secret-from-yaml
