apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort  # 可以是 NodePort 或者 LoadBalancer
  ports:
    - port: 3000
      nodePort: 30390 # 對外 port, 若是沒有指定則會隨機生成
      targetPort: 3000
      protocol: TCP # TCP or UDP
  selector:
    app: my-deployment