apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: webserver
  annotations:
    version: latest
    release_date: 2021-02-06
spec:
  containers:
  - name: pod-demo
    image: zxcvbnius/docker-demo
    ports:
      - containerPort: 3000