apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 3 # 複製三份
  selector: # 選取 label 為 hello-pod-v1 的 pod
    app: hello-pod-v1
  template: # 定義 pod 的資訊以及 docker image
    metadata:
      labels:
        app: hello-pod-v1
    spec: # 描述 container 資訊
      containers:
      - name: my-pod
        image: zxcvbnius/docker-demo
        ports:
        - containerPort: 3000