apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
    - name: apiserver
      image: zxcvbnius/docker-demo
      volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
  volumes:
    - name: tmp-volume
      hostPath:
        path: /tmp
        type: Directory