apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  containers:
    - name: mysql-server
      image: mysql:5.7
      ports:
        - containerPort: 3306
          name: mysql-port
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-root-password