apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress-deployment
  ports:
    - nodePort: 30300
      port: 3000
      protocol: TCP
      targetPort: wordpress-port